
name: Game Engine

on:
  issues:
    types: [opened]

jobs:
  run-turn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Game Turn
        run: python3 game.py "${{ github.event.issue.title }}"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md game-state.yml
          git commit -m "Game turn processed"
          git push
