name: Waka README stats

on:
  schedule:
    - cron: "0 11 * * *" # run every day at 11:00 UTC (~6am US/Eastern standard time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with dev metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
